services:
  airflow:
    image: apache/airflow:2.9.3-python3.11
    command: standalone
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "scikit-learn==1.9.1 pandas==2.3.3 joblib==1.6.0 onnx==1.22.0 onnxruntime==1.30.0 skl2onnx==1.20.0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml:/opt/airflow/ml
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
      - "./archive (1).zip:/opt/airflow/archive (1).zip:ro"
      - airflow_home:/opt/airflow
    ports:
      - "8080:8080"

volumes:
  airflow_home:
